// Generated by Dagger (https://dagger.dev).
package com.example.todolist.ui.viewmodel;

import com.example.todolist.repository.TasksRepository;
import dagger.internal.Factory;
import javax.inject.Provider;

@SuppressWarnings({
    "unchecked",
    "rawtypes"
})
public final class TaskListViewModel_Factory implements Factory<TaskListViewModel> {
  private final Provider<TasksRepository> tasksRepositoryProvider;

  public TaskListViewModel_Factory(Provider<TasksRepository> tasksRepositoryProvider) {
    this.tasksRepositoryProvider = tasksRepositoryProvider;
  }

  @Override
  public TaskListViewModel get() {
    return newInstance(tasksRepositoryProvider.get());
  }

  public static TaskListViewModel_Factory create(
      Provider<TasksRepository> tasksRepositoryProvider) {
    return new TaskListViewModel_Factory(tasksRepositoryProvider);
  }

  public static TaskListViewModel newInstance(TasksRepository tasksRepository) {
    return new TaskListViewModel(tasksRepository);
  }
}
